import type { Metadata } from "next";
import { Cabin, Mulish, Petrona } from "next/font/google";
import "./globals.css";
const mulish = Mulish({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mulish"
});
const cabin = Cabin({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-cabin"
});
const petrona = Petrona({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-petrona"
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${mulish.variable} ${petrona.variable} ${cabin.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
